### ISSUE TITLE
missing code of rfconv？

### ISSUE THREAD

**Issue by snowzjy** [zhanghang1989/ResNeSt#17]
Hi!

In the torch.resnet.py file has code below:

if rectified_conv:
            from rfconv import RFConv2d

But I can't find file rfconv

**Comment by xialuxi** [comment]
https://github.com/zhanghang1989/PyTorch-Encoding/blob/b872eb8cc01f6e0dde3d9acfb5846abe5c3a450a/encoding/nn/rectify.py

**Comment by zhanghang1989** [comment]
> https://github.com/zhanghang1989/PyTorch-Encoding/blob/b872eb8cc01f6e0dde3d9acfb5846abe5c3a450a/encoding/nn/rectify.py

Thanks for sharing the pointer. I will share an arXiv report later. Please kindly do not distribute it for now.

If you use it in your research, please cite it as:

```
@article{zhang2020rectified,
title={Rectified Convolution},
author={Zhang, Hang},
journal={arXiv preprint},
year={2020}
}
```

**Comment by snowzjy** [comment]
> > https://github.com/zhanghang1989/PyTorch-Encoding/blob/b872eb8cc01f6e0dde3d9acfb5846abe5c3a450a/encoding/nn/rectify.py
> 
> Thanks for sharing the pointer. I will share an arXiv report later. Please kindly do not distribute it for now.
> 
> If you use it in your research, please cite it as:
> 
> ```
> @article{zhang2020rectified,
> title={Rectified Convolution},
> author={Zhang, Hang},
> journal={arXiv preprint},
> year={2020}
> }
> ```

**Comment by xiaopanchen** [comment]
In order to use rfconv, I have copy the folder "functions、lib、nn" to my project, but there are errors below.
出现了下面的错误
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 866, in _jit_compile
    with_cuda=with_cuda)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 919, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1078, in _build_extension_module
    message += ": {}".format(error.output.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 1043: invalid continuation byte

**Comment by zhanghang1989** [comment]
Could you install the toolkit directly?
https://hangzhang.org/PyTorch-Encoding/notes/compile.html

**Comment by xiaopanchen** [comment]
> Could you install the toolkit directly?
> https://hangzhang.org/PyTorch-Encoding/notes/compile.html

I have install from the source. And, I use the package like this. "# from rfconv import RFConv2d
from encoding.nn.rectify import RFConv2d". But, the errors did not vanish.

C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py:209: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1066, in _build_extension_module
    check=True)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/fast-reid-20200711/tools/train_net.py", line 15, in <module>
    from fastreid.engine import DefaultTrainer, default_argument_parser, default_setup, launch
  File "D:\fast-reid-20200711\fastreid\engine\__init__.py", line 14, in <module>
    from .defaults import *
  File "D:\fast-reid-20200711\fastreid\engine\defaults.py", line 24, in <module>
    from fastreid.modeling.meta_arch import build_model
  File "D:\fast-reid-20200711\fastreid\modeling\__init__.py", line 7, in <module>
    from .meta_arch import build_model
  File "D:\fast-reid-20200711\fastreid\modeling\meta_arch\__init__.py", line 11, in <module>
    from .baseline import Baseline
  File "D:\fast-reid-20200711\fastreid\modeling\meta_arch\baseline.py", line 11, in <module>
    from fastreid.modeling.backbones import build_backbone
  File "D:\fast-reid-20200711\fastreid\modeling\backbones\__init__.py", line 11, in <module>
    from .resnest import build_resnest_backbone
  File "D:\fast-reid-20200711\fastreid\modeling\backbones\resnest.py", line 10, in <module>
    from encoding.nn.rectify import RFConv2d
  File "C:\ProgramData\Anaconda3\lib\site-packages\encoding\__init__.py", line 13, in <module>
    from . import nn, functions, parallel, utils, models, datasets, transforms
  File "C:\ProgramData\Anaconda3\lib\site-packages\encoding\nn\__init__.py", line 12, in <module>
    from .encoding import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\encoding\nn\encoding.py", line 18, in <module>
    from ..functions import scaled_l2, aggregate, pairwise_cosine
  File "C:\ProgramData\Anaconda3\lib\site-packages\encoding\functions\__init__.py", line 2, in <module>
    from .encoding import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\encoding\functions\encoding.py", line 14, in <module>
    from .. import lib
  File "C:\ProgramData\Anaconda3\lib\site-packages\encoding\lib\__init__.py", line 16, in <module>
    ], build_directory=cpu_path, verbose=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 680, in load
    is_python_module)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 866, in _jit_compile
    with_cuda=with_cuda)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 919, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1078, in _build_extension_module
    message += ": {}".format(error.output.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 1077: invalid continuation byte

**Comment by zhanghang1989** [comment]
Please follow the detailed steps to install `ninja` first:
https://hangzhang.org/PyTorch-Encoding/notes/compile.html#detailed-steps

Also make sure the PyTorch version is 1.4.0.

**Comment by xiaopanchen** [comment]
> Please follow the detailed steps to install `ninja` first:
> https://hangzhang.org/PyTorch-Encoding/notes/compile.html#detailed-steps
> 
> Also make sure the PyTorch version is 1.4.0.

yes, the pytorch is 1.4.0

**Comment by xiaopanchen** [comment]
> Please follow the detailed steps to install `ninja` first:
> https://hangzhang.org/PyTorch-Encoding/notes/compile.html#detailed-steps
> 
> Also make sure the PyTorch version is 1.4.0.

How to install ninja in Windows 10?

**Comment by zhanghang1989** [comment]
Sorry that I am not familiar with Windows system. The command should work for mac and ubuntu.

**Comment by xiaopanchen** [comment]
> Sorry that I am not familiar with Windows system. The command should work for mac and ubuntu.

Than  you very much.

**Comment by zhanghang1989** [comment]
Open sourced at
https://github.com/zhanghang1989/RFConv
